# SPDX-License-Identifier: GPL-2.0
FROM hub.oepkgs.net/openeuler/openeuler:24.03-lts

LABEL name=mptcp-upstream-virtme-docker

# dependencies for the script
RUN yum update -y && \
	yum upgrade -y && \
	yum install -y \
		make ncurses-devel gcc openssl-devel bc bison byacc automake cmake \
		elfutils-libelf-devel flex git curl tar qemu-kvm sudo expect \
		python3 python3-pip python3-setuptools file \
		busybox coreutils python3-requests libvirt-client udev \
		iputils ethtool kbd rsync ccache nc \
		ca-certificates gnupg2 net-tools kmod \
		dbus-devel libnl3-devel libibverbs-devel \
		tcpdump \
		pkgconfig libmnl-devel \
		clang clang-tools-extra lld llvm llvm-devel libcap-devel \
		gdb gdb-gdbserver crash dwarves strace trace-cmd \
		iptables ebtables nftables \
		vim psmisc bash-completion less jq \
		gettext libevent-devel newt python3-newt tmux \
		libdwarf-devel numactl-devel libzstd-devel libunwind-devel python3-devel python3-setuptools binutils-devel libbabeltrace-devel systemtap-sdt-devel perl-devel python3-docutils \
		libxml2-devel sqlite-devel gtk3-devel gtk2-devel perl-JSON \
		zstd \
		wget xz lftp cpio \
		cscope \
		bpftrace \
		patch \
		&& \
	yum clean all

# byobu (not to have a dep to iproute2)
ARG BYOBU_URL="https://github.com/dustinkirkland/byobu/archive/refs/tags/6.13.tar.gz"
ARG BYOBU_SUM="9690c629588e8f95d16b2461950d39934faaf8005dd2a283886d4e3bd6c86df6  byobu.tar.gz"
RUN cd /opt && \
	curl -L "${BYOBU_URL}" -o byobu.tar.gz && \
	echo "${BYOBU_SUM}" | sha256sum -c && \
	tar xzf byobu.tar.gz && \
	cd byobu-*/ && \
		./autogen.sh && \
		./configure --prefix=/usr && \
		make -j"$(nproc)" -l"$(nproc)" && \
		make install

# packetdrill
ARG PACKETDRILL_GIT_URL="https://github.com/multipath-tcp/packetdrill.git"
ARG PACKETDRILL_GIT_BRANCH="mptcp-net-next"
ENV PACKETDRILL_GIT_BRANCH="${PACKETDRILL_GIT_BRANCH}"
RUN cd /opt && \
	git clone "${PACKETDRILL_GIT_URL}" && \
	cd packetdrill && \
		git checkout "${PACKETDRILL_GIT_BRANCH}" && \
		cd gtests/net/packetdrill/ && \
			./configure && \
			make -j"$(nproc)" -l"$(nproc)" && \
			ln -s /opt/packetdrill/gtests/net/packetdrill/packetdrill \
			      /opt/packetdrill/gtests/net/packetdrill/run_all.py \
				/usr/sbin/

# Sparse
ARG SPARSE_GIT_URL="https://git.kernel.org/pub/scm/devel/sparse/sparse.git"
ARG SPARSE_GIT_SHA="fbdde3127b83e6d09e0ba808d7925dd84407f3c6" # include a fix for __builtin_strlen
COPY sparse-fix-__builtin_strlen.patch /opt/
RUN cd /opt && \
	git clone "${SPARSE_GIT_URL}" sparse && \
	cd "sparse" && \
		git checkout "${SPARSE_GIT_SHA}" && \
		patch -p1 --merge < /opt/sparse-fix-__builtin_strlen.patch && \
		make -j"$(nproc)" -l"$(nproc)" && \
		make PREFIX=/usr install && \
		cd .. && \
	rm -rf "sparse"

# Pahole
#ARG PAHOLE_GIT_URL="git://git.kernel.org/pub/scm/devel/pahole/pahole.git"
#ARG PAHOLE_GIT_SHA="v1.31"
#RUN cd /opt && \
#	git clone "${PAHOLE_GIT_URL}" pahole && \
#	cd "pahole" && \
#		git checkout "${PAHOLE_GIT_SHA}" && \
#		git submodule update --init --recursive && \
#		mkdir build && \
#		cd build && \
#		cmake .. && \
#		make -j"$(nproc)" -l"$(nproc)" && \
#		make install && \
#		ldconfig && \
#		cd .. && \
#	rm -rf "pahole"

# iproute
ARG IPROUTE2_GIT_URL="https://git.kernel.org/pub/scm/network/iproute2/iproute2.git"
ARG IPROUTE2_GIT_SHA="v6.18.0"
RUN cd /opt && \
	git clone "${IPROUTE2_GIT_URL}" iproute2 && \
	cd iproute2 && \
		git checkout "${IPROUTE2_GIT_SHA}" && \
		./configure --color=auto && \
		make -j"$(nproc)" -l"$(nproc)" && \
		make install

# Virtme NG
ARG VIRTME_NG_VERSION="1.40"
RUN pip3 install --break-system-packages virtme-ng=="${VIRTME_NG_VERSION}"
# temp workaround, see: https://github.com/arighi/virtme-ng/issues/353
#RUN sed -i 's/-o cache=always //' /usr/local/lib/python3.11/dist-packages/virtme/commands/run.py

# to quickly shutdown the VM and more
RUN for i in /usr/lib/klibc/bin/*; do \
	type "$(basename "${i}")" >/dev/null 2>&1 || ln -sv "${i}" /usr/sbin/; \
    done

# CCache for quicker builds with default colours
# Note: use 'ccache -M xG' to increase max size, default is 5GB
ENV PATH=/usr/lib/ccache:/opt/virtme-ng:${PATH}
ENV CCACHE_COMPRESS=true
ENV KBUILD_BUILD_TIMESTAMP="0"
ENV GCC_COLORS=error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01

COPY entrypoint.sh *.py *.yml /

ENTRYPOINT ["/entrypoint.sh"]
